# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: <atlas-gps-server>
# Command to start on workspace startup (optional)
tasks:
  - init: pip install node
    command: pip install mysql php express look && node webserver/web-server.js
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
    onOpen: open-browser
